//
// auto-generated by ops.py
//

int xdim0_poisson_kernel_stencil;
int xdim1_poisson_kernel_stencil;


//user function



void poisson_kernel_stencil_c_wrapper(
  float * restrict u_p,
  float * restrict u2_p,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      const ptr_float u = { u_p + n_x*1 + n_y * xdim0_poisson_kernel_stencil*1, xdim0_poisson_kernel_stencil};
      ptr_float u2 = { u2_p + n_x*1 + n_y * xdim1_poisson_kernel_stencil*1, xdim1_poisson_kernel_stencil};
      
  OPS_ACC(u2, 0,0) = OPS_ACC(u, -1,1)*(-0.07f) + OPS_ACC(u, 0,1) * (-0.06f) + OPS_ACC(u, 1,1)*(-0.05f) \
	    + OPS_ACC(u, -1,0)*(-0.08f) + OPS_ACC(u, 0,0)*0.36f + OPS_ACC(u, 1,0)*(-0.04f) + \
	    OPS_ACC(u, -1,-1)*(-0.01f) + OPS_ACC(u, 0,-1)*(-0.02f) + OPS_ACC(u, 1,-1)*(-0.03f);

    }
  }
}
