//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim5_calc_ytemp2_kernel;
int ydim5_calc_ytemp2_kernel;
int xdim6_calc_ytemp2_kernel;
int ydim6_calc_ytemp2_kernel;
int xdim7_calc_ytemp2_kernel;
int ydim7_calc_ytemp2_kernel;

//user function
#pragma acc routine
inline 
void calc_ytemp2_kernel(const int *dispx,
  const int *dispy,
  const int *dispz,
  const int *idx,
  const float *dt,
  const ptrm_float  yy,
  ptrm_float k,
  ptrm_float ytemp) {

  for (int i=0;i<6;i++) {
    OPS_ACC(k, i,0,0,0) = OPS_ACC(k, i,0,0,0)* *dt;
    OPS_ACC(ytemp, i,0,0,0) = OPS_ACC(yy, i,0,0,0) + OPS_ACC(k, i,0,0,0);
  }

}


void calc_ytemp2_kernel_c_wrapper(
  int p_a0,
  int p_a1,
  int p_a2,
  int *p_a3,
  float p_a4,
  float *p_a5,
  float *p_a6,
  float *p_a7,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a5,p_a6,p_a7)
  #pragma acc loop
  #endif
  for ( int n_z=0; n_z<z_size; n_z++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_y=0; n_y<y_size; n_y++ ){
      #ifdef OPS_GPU
      #pragma acc loop
      #endif
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        #ifdef OPS_SOA
        const ptrm_float ptr5 = {  p_a5 + n_x*1*6 + n_y*xdim5_calc_ytemp2_kernel*1*6 + n_z*xdim5_calc_ytemp2_kernel*ydim5_calc_ytemp2_kernel*1*6, xdim5_calc_ytemp2_kernel, ydim5_calc_ytemp2_kernel, zdim5_calc_ytemp2_kernel};
        #else
        const ptrm_float ptr5 = {  p_a5 + n_x*1*6 + n_y*xdim5_calc_ytemp2_kernel*1*6 + n_z*xdim5_calc_ytemp2_kernel*ydim5_calc_ytemp2_kernel*1*6, xdim5_calc_ytemp2_kernel, ydim5_calc_ytemp2_kernel, 6};
        #endif
        #ifdef OPS_SOA
        ptrm_float ptr6 = {  p_a6 + n_x*1*6 + n_y*xdim6_calc_ytemp2_kernel*1*6 + n_z*xdim6_calc_ytemp2_kernel*ydim6_calc_ytemp2_kernel*1*6, xdim6_calc_ytemp2_kernel, ydim6_calc_ytemp2_kernel, zdim6_calc_ytemp2_kernel};
        #else
        ptrm_float ptr6 = {  p_a6 + n_x*1*6 + n_y*xdim6_calc_ytemp2_kernel*1*6 + n_z*xdim6_calc_ytemp2_kernel*ydim6_calc_ytemp2_kernel*1*6, xdim6_calc_ytemp2_kernel, ydim6_calc_ytemp2_kernel, 6};
        #endif
        #ifdef OPS_SOA
        ptrm_float ptr7 = {  p_a7 + n_x*1*6 + n_y*xdim7_calc_ytemp2_kernel*1*6 + n_z*xdim7_calc_ytemp2_kernel*ydim7_calc_ytemp2_kernel*1*6, xdim7_calc_ytemp2_kernel, ydim7_calc_ytemp2_kernel, zdim7_calc_ytemp2_kernel};
        #else
        ptrm_float ptr7 = {  p_a7 + n_x*1*6 + n_y*xdim7_calc_ytemp2_kernel*1*6 + n_z*xdim7_calc_ytemp2_kernel*ydim7_calc_ytemp2_kernel*1*6, xdim7_calc_ytemp2_kernel, ydim7_calc_ytemp2_kernel, 6};
        #endif
        calc_ytemp2_kernel(  &p_a0,
           &p_a1,
           &p_a2,
          arg_idx,
           &p_a4,
          ptr5,
          ptr6,
          ptr7 );

      }
    }
  }
}
