//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim4_fd3d_pml_kernel;
int ydim4_fd3d_pml_kernel;
int xdim5_fd3d_pml_kernel;
int ydim5_fd3d_pml_kernel;
int xdim6_fd3d_pml_kernel;
int ydim6_fd3d_pml_kernel;
int xdim7_fd3d_pml_kernel;
int ydim7_fd3d_pml_kernel;

//user function
#pragma acc routine
inline 
void fd3d_pml_kernel(const int *dispx,
  const int *dispy,
  const int *dispz,
  const int *idx,
  const ptr_float rho,
  const ptr_float mu,
  const ptrm_float  yy,
  ptrm_float  dyy) {


  const float c[9] = {0.0035714285714285713,-0.0380952380952381,0.2,-0.8,0.0,0.8,-0.2,0.0380952380952381,-0.0035714285714285713};
  float invdx = 1.0 / dx;
  float invdy = 1.0 / dy;
  float invdz = 1.0 / dz;
  int xbeg=half;
  int xend=nx-half;
  int ybeg=half;
  int yend=ny-half;
  int zbeg=half;
  int zend=nz-half;
  int xpmlbeg=xbeg+pml_width;
  int ypmlbeg=ybeg+pml_width;
  int zpmlbeg=zbeg+pml_width;
  int xpmlend=xend-pml_width;
  int ypmlend=yend-pml_width;
  int zpmlend=zend-pml_width;

  float sigma = OPS_ACC(mu, 0,0,0)/OPS_ACC(rho, 0,0,0);
  float sigmax=0.0;
  float sigmay=0.0;
  float sigmaz=0.0;
  if(idx[0]<=xbeg+pml_width){
    sigmax = (xbeg+pml_width-idx[0])*sigma * 0.1f;
  }
  if(idx[0]>=xend-pml_width){
    sigmax=(idx[0]-(xend-pml_width))*sigma * 0.1f;
  }
  if(idx[1]<=ybeg+pml_width){
    sigmay=(ybeg+pml_width-idx[1])*sigma * 0.1f;
  }
  if(idx[1]>=yend-pml_width){
    sigmay=(idx[1]-(yend-pml_width))*sigma * 0.1f;
  }
  if(idx[2]<=zbeg+pml_width){
    sigmaz=(zbeg+pml_width-idx[2])*sigma * 0.1f;
  }
  if(idx[2]>=zend-pml_width){
    sigmaz=(idx[2]-(zend-pml_width))*sigma * 0.1f;
  }



  float px = OPS_ACC(yy, 0,0,0,0);
  float py = OPS_ACC(yy, 1,0,0,0);
  float pz = OPS_ACC(yy, 2,0,0,0);

  float vx = OPS_ACC(yy, 3,0,0,0);
  float vy = OPS_ACC(yy, 4,0,0,0);
  float vz = OPS_ACC(yy, 5,0,0,0);

  float vxx=0.0;
  float vxy=0.0;
  float vxz=0.0;

  float vyx=0.0;
  float vyy=0.0;
  float vyz=0.0;

  float vzx=0.0;
  float vzy=0.0;
  float vzz=0.0;

  float pxx=0.0;
  float pxy=0.0;
  float pxz=0.0;

  float pyx=0.0;
  float pyy=0.0;
  float pyz=0.0;

  float pzx=0.0;
  float pzy=0.0;
  float pzz=0.0;

  for(int i=-half;i<=half;i++){
    pxx += OPS_ACC(yy, 0,i,0,0)*c[i+half];
    pyx += OPS_ACC(yy, 1,i,0,0)*c[i+half];
    pzx += OPS_ACC(yy, 2,i,0,0)*c[i+half];

    vxx += OPS_ACC(yy, 3,i,0,0)*c[i+half];
    vyx += OPS_ACC(yy, 4,i,0,0)*c[i+half];
    vzx += OPS_ACC(yy, 5,i,0,0)*c[i+half];

    pxy += OPS_ACC(yy, 0,0,i,0)*c[i+half];
    pyy += OPS_ACC(yy, 1,0,i,0)*c[i+half];
    pzy += OPS_ACC(yy, 2,0,i,0)*c[i+half];

    vxy += OPS_ACC(yy, 3,0,i,0)*c[i+half];
    vyy += OPS_ACC(yy, 4,0,i,0)*c[i+half];
    vzy += OPS_ACC(yy, 5,0,i,0)*c[i+half];

    pxz += OPS_ACC(yy, 0,0,0,i)*c[i+half];
    pyz += OPS_ACC(yy, 1,0,0,i)*c[i+half];
    pzz += OPS_ACC(yy, 2,0,0,i)*c[i+half];

    vxz += OPS_ACC(yy, 3,0,0,i)*c[i+half];
    vyz += OPS_ACC(yy, 4,0,0,i)*c[i+half];
    vzz += OPS_ACC(yy, 5,0,0,i)*c[i+half];
  }

  pxx *= invdx;
  pyx *= invdx;
  pzx *= invdx;

  vxx *= invdx;
  vyx *= invdx;
  vzx *= invdx;

  pxy *= invdy;
  pyy *= invdy;
  pzy *= invdy;

  vxy *= invdy;
  vyy *= invdy;
  vzy *= invdy;

  pxz *= invdz;
  pyz *= invdz;
  pzz *= invdz;

  vxz *= invdz;
  vyz *= invdz;
  vzz *= invdz;

  OPS_ACC(dyy, 0,0,0,0)=vxx/OPS_ACC(rho, 0,0,0) - sigmax*px;
  OPS_ACC(dyy, 3,0,0,0)=(pxx+pyx+pxz)*OPS_ACC(mu, 0,0,0) - sigmax*vx;

  OPS_ACC(dyy, 1,0,0,0)=vyy/OPS_ACC(rho, 0,0,0) - sigmay*py;
  OPS_ACC(dyy, 4,0,0,0)=(pxy+pyy+pyz)*OPS_ACC(mu, 0,0,0) - sigmay*vy;

  OPS_ACC(dyy, 2,0,0,0)=vzz/OPS_ACC(rho, 0,0,0) - sigmaz*pz;
  OPS_ACC(dyy, 5,0,0,0)=(pxz+pyz+pzz)*OPS_ACC(mu, 0,0,0) - sigmaz*vz;

}


void fd3d_pml_kernel_c_wrapper(
  int p_a0,
  int p_a1,
  int p_a2,
  int *p_a3,
  float *p_a4,
  float *p_a5,
  float *p_a6,
  float *p_a7,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a4,p_a5,p_a6,p_a7)
  #pragma acc loop
  #endif
  for ( int n_z=0; n_z<z_size; n_z++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_y=0; n_y<y_size; n_y++ ){
      #ifdef OPS_GPU
      #pragma acc loop
      #endif
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        const ptr_float ptr4 = {  p_a4 + n_x*1*1 + n_y*xdim4_fd3d_pml_kernel*1*1 + n_z*xdim4_fd3d_pml_kernel*ydim4_fd3d_pml_kernel*1*1, xdim4_fd3d_pml_kernel, ydim4_fd3d_pml_kernel};
        const ptr_float ptr5 = {  p_a5 + n_x*1*1 + n_y*xdim5_fd3d_pml_kernel*1*1 + n_z*xdim5_fd3d_pml_kernel*ydim5_fd3d_pml_kernel*1*1, xdim5_fd3d_pml_kernel, ydim5_fd3d_pml_kernel};
        #ifdef OPS_SOA
        const ptrm_float ptr6 = {  p_a6 + n_x*1*6 + n_y*xdim6_fd3d_pml_kernel*1*6 + n_z*xdim6_fd3d_pml_kernel*ydim6_fd3d_pml_kernel*1*6, xdim6_fd3d_pml_kernel, ydim6_fd3d_pml_kernel, zdim6_fd3d_pml_kernel};
        #else
        const ptrm_float ptr6 = {  p_a6 + n_x*1*6 + n_y*xdim6_fd3d_pml_kernel*1*6 + n_z*xdim6_fd3d_pml_kernel*ydim6_fd3d_pml_kernel*1*6, xdim6_fd3d_pml_kernel, ydim6_fd3d_pml_kernel, 6};
        #endif
        #ifdef OPS_SOA
        ptrm_float ptr7 = {  p_a7 + n_x*1*6 + n_y*xdim7_fd3d_pml_kernel*1*6 + n_z*xdim7_fd3d_pml_kernel*ydim7_fd3d_pml_kernel*1*6, xdim7_fd3d_pml_kernel, ydim7_fd3d_pml_kernel, zdim7_fd3d_pml_kernel};
        #else
        ptrm_float ptr7 = {  p_a7 + n_x*1*6 + n_y*xdim7_fd3d_pml_kernel*1*6 + n_z*xdim7_fd3d_pml_kernel*ydim7_fd3d_pml_kernel*1*6, xdim7_fd3d_pml_kernel, ydim7_fd3d_pml_kernel, 6};
        #endif
        fd3d_pml_kernel(  &p_a0,
           &p_a1,
           &p_a2,
          arg_idx,
          ptr4,
          ptr5,
          ptr6,
          ptr7 );

      }
    }
  }
}
