//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim5_final_update_kernel;
int ydim5_final_update_kernel;
int xdim6_final_update_kernel;
int ydim6_final_update_kernel;
int xdim7_final_update_kernel;
int ydim7_final_update_kernel;
int xdim8_final_update_kernel;
int ydim8_final_update_kernel;
int xdim9_final_update_kernel;
int ydim9_final_update_kernel;

//user function
#pragma acc routine
inline 
void final_update_kernel(const int *dispx,
  const int *dispy,
  const int *dispz,
  const int *idx,
  const float *dt,
  const ptrm_float k1,
  const ptrm_float k2,
  const ptrm_float  k3,
  ptrm_float  k4,
  ptrm_float yy) {

  for (int i=0;i<6;i++) {
    OPS_ACC(k4, i,0,0,0) = OPS_ACC(k4, i,0,0,0)* *dt;
    OPS_ACC(yy, i,0,0,0) = OPS_ACC(yy, i,0,0,0) +
      OPS_ACC(k1, i,0,0,0)/6.0f +
      OPS_ACC(k2, i,0,0,0)/3.0f +
      OPS_ACC(k3, i,0,0,0)/3.0f +
      OPS_ACC(k4, i,0,0,0)/6.0f;
  }

}


void final_update_kernel_c_wrapper(
  int p_a0,
  int p_a1,
  int p_a2,
  int *p_a3,
  float p_a4,
  float *p_a5,
  float *p_a6,
  float *p_a7,
  float *p_a8,
  float *p_a9,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a5,p_a6,p_a7,p_a8,p_a9)
  #pragma acc loop
  #endif
  for ( int n_z=0; n_z<z_size; n_z++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_y=0; n_y<y_size; n_y++ ){
      #ifdef OPS_GPU
      #pragma acc loop
      #endif
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        #ifdef OPS_SOA
        const ptrm_float ptr5 = {  p_a5 + n_x*1*6 + n_y*xdim5_final_update_kernel*1*6 + n_z*xdim5_final_update_kernel*ydim5_final_update_kernel*1*6, xdim5_final_update_kernel, ydim5_final_update_kernel, zdim5_final_update_kernel};
        #else
        const ptrm_float ptr5 = {  p_a5 + n_x*1*6 + n_y*xdim5_final_update_kernel*1*6 + n_z*xdim5_final_update_kernel*ydim5_final_update_kernel*1*6, xdim5_final_update_kernel, ydim5_final_update_kernel, 6};
        #endif
        #ifdef OPS_SOA
        const ptrm_float ptr6 = {  p_a6 + n_x*1*6 + n_y*xdim6_final_update_kernel*1*6 + n_z*xdim6_final_update_kernel*ydim6_final_update_kernel*1*6, xdim6_final_update_kernel, ydim6_final_update_kernel, zdim6_final_update_kernel};
        #else
        const ptrm_float ptr6 = {  p_a6 + n_x*1*6 + n_y*xdim6_final_update_kernel*1*6 + n_z*xdim6_final_update_kernel*ydim6_final_update_kernel*1*6, xdim6_final_update_kernel, ydim6_final_update_kernel, 6};
        #endif
        #ifdef OPS_SOA
        const ptrm_float ptr7 = {  p_a7 + n_x*1*6 + n_y*xdim7_final_update_kernel*1*6 + n_z*xdim7_final_update_kernel*ydim7_final_update_kernel*1*6, xdim7_final_update_kernel, ydim7_final_update_kernel, zdim7_final_update_kernel};
        #else
        const ptrm_float ptr7 = {  p_a7 + n_x*1*6 + n_y*xdim7_final_update_kernel*1*6 + n_z*xdim7_final_update_kernel*ydim7_final_update_kernel*1*6, xdim7_final_update_kernel, ydim7_final_update_kernel, 6};
        #endif
        #ifdef OPS_SOA
        ptrm_float ptr8 = {  p_a8 + n_x*1*6 + n_y*xdim8_final_update_kernel*1*6 + n_z*xdim8_final_update_kernel*ydim8_final_update_kernel*1*6, xdim8_final_update_kernel, ydim8_final_update_kernel, zdim8_final_update_kernel};
        #else
        ptrm_float ptr8 = {  p_a8 + n_x*1*6 + n_y*xdim8_final_update_kernel*1*6 + n_z*xdim8_final_update_kernel*ydim8_final_update_kernel*1*6, xdim8_final_update_kernel, ydim8_final_update_kernel, 6};
        #endif
        #ifdef OPS_SOA
        ptrm_float ptr9 = {  p_a9 + n_x*1*6 + n_y*xdim9_final_update_kernel*1*6 + n_z*xdim9_final_update_kernel*ydim9_final_update_kernel*1*6, xdim9_final_update_kernel, ydim9_final_update_kernel, zdim9_final_update_kernel};
        #else
        ptrm_float ptr9 = {  p_a9 + n_x*1*6 + n_y*xdim9_final_update_kernel*1*6 + n_z*xdim9_final_update_kernel*ydim9_final_update_kernel*1*6, xdim9_final_update_kernel, ydim9_final_update_kernel, 6};
        #endif
        final_update_kernel(  &p_a0,
           &p_a1,
           &p_a2,
          arg_idx,
           &p_a4,
          ptr5,
          ptr6,
          ptr7,
          ptr8,
          ptr9 );

      }
    }
  }
}
