//
// auto-generated by ops.py//

#include "./OpenACC/poisson_common.h"

#include <openacc.h>

void ops_init_backend() {acc_set_device_num(ops_get_proc()%acc_get_num_devices(acc_device_nvidia),acc_device_nvidia); ops_device_initialised_externally = 1;}

void ops_decl_const_char(int dim, char const *type,
int size, char *dat, char const *name){
  if (!strcmp(name,"dx")) {
    dx = *(float*)dat;
  }
  else
  if (!strcmp(name,"dy")) {
    dy = *(float*)dat;
  }
  else
  if (!strcmp(name,"dz")) {
    dz = *(float*)dat;
  }
  else
  if (!strcmp(name,"nx")) {
    nx = *(int*)dat;
  }
  else
  if (!strcmp(name,"ny")) {
    ny = *(int*)dat;
  }
  else
  if (!strcmp(name,"nz")) {
    nz = *(int*)dat;
  }
  else
  if (!strcmp(name,"pml_width")) {
    pml_width = *(int*)dat;
  }
  else
  if (!strcmp(name,"half")) {
    half = *(int*)dat;
  }
  else
  if (!strcmp(name,"order")) {
    order = *(int*)dat;
  }
  else
  {
    printf("error: unknown const name\n"); exit(1);
  }
}

//user kernel files
#include "rtm_kernel_populate_openacc_kernel.cpp"
#include "fd3d_pml_kernel_openacc_kernel.cpp"
#include "calc_ytemp_kernel_openacc_kernel.cpp"
#include "calc_ytemp2_kernel_openacc_kernel.cpp"
#include "final_update_kernel_openacc_kernel.cpp"
