//
// auto-generated by ops.py//

#include "./OpenACC/poisson_common.h"

#include <openacc.h>

//user kernel files
#include "rtm_kernel_populate_openacc_kernel_c.c"
#include "fd3d_pml_kernel_openacc_kernel_c.c"
#include "calc_ytemp_kernel_openacc_kernel_c.c"
#include "calc_ytemp2_kernel_openacc_kernel_c.c"
#include "final_update_kernel_openacc_kernel_c.c"
