//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim4_rtm_kernel_populate;
int ydim4_rtm_kernel_populate;
int xdim5_rtm_kernel_populate;
int ydim5_rtm_kernel_populate;
int xdim6_rtm_kernel_populate;
int ydim6_rtm_kernel_populate;

//user function
#pragma acc routine
inline 
void rtm_kernel_populate(const int *dispx,
  const int *dispy,
  const int *dispz,
  const int *idx,
  ptr_float rho,
  ptr_float mu,
  ptrm_float yy) {




  float x = 1.0*((float)(idx[0]-nx/2)/nx);
  float y = 1.0*((float)(idx[1]-ny/2)/ny);
  float z = 1.0*((float)(idx[2]-nz/2)/nz);

  const float C = 1.0f;
  const float r0 = 0.001f;
  OPS_ACC(rho, 0,0,0) = 1000.0f;
  OPS_ACC(mu, 0,0,0) = 0.001f;






  OPS_ACC(yy, 0,0,0,0) = (1./3.)*C*exp(-(x*x+y*y+z*z)/r0);



}


void rtm_kernel_populate_c_wrapper(
  int p_a0,
  int p_a1,
  int p_a2,
  int *p_a3,
  float *p_a4,
  float *p_a5,
  float *p_a6,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a4,p_a5,p_a6)
  #pragma acc loop
  #endif
  for ( int n_z=0; n_z<z_size; n_z++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_y=0; n_y<y_size; n_y++ ){
      #ifdef OPS_GPU
      #pragma acc loop
      #endif
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        ptr_float ptr4 = {  p_a4 + n_x*1*1 + n_y*xdim4_rtm_kernel_populate*1*1 + n_z*xdim4_rtm_kernel_populate*ydim4_rtm_kernel_populate*1*1, xdim4_rtm_kernel_populate, ydim4_rtm_kernel_populate};
        ptr_float ptr5 = {  p_a5 + n_x*1*1 + n_y*xdim5_rtm_kernel_populate*1*1 + n_z*xdim5_rtm_kernel_populate*ydim5_rtm_kernel_populate*1*1, xdim5_rtm_kernel_populate, ydim5_rtm_kernel_populate};
        #ifdef OPS_SOA
        ptrm_float ptr6 = {  p_a6 + n_x*1*6 + n_y*xdim6_rtm_kernel_populate*1*6 + n_z*xdim6_rtm_kernel_populate*ydim6_rtm_kernel_populate*1*6, xdim6_rtm_kernel_populate, ydim6_rtm_kernel_populate, zdim6_rtm_kernel_populate};
        #else
        ptrm_float ptr6 = {  p_a6 + n_x*1*6 + n_y*xdim6_rtm_kernel_populate*1*6 + n_z*xdim6_rtm_kernel_populate*ydim6_rtm_kernel_populate*1*6, xdim6_rtm_kernel_populate, ydim6_rtm_kernel_populate, 6};
        #endif
        rtm_kernel_populate(  &p_a0,
           &p_a1,
           &p_a2,
          arg_idx,
          ptr4,
          ptr5,
          ptr6 );

      }
    }
  }
}
