//
// auto-generated by ops.py
//

int xdim0_poisson_kernel_update;
int ydim0_poisson_kernel_update;
int xdim1_poisson_kernel_update;
int ydim1_poisson_kernel_update;


//user function



void poisson_kernel_update_c_wrapper(
  float * restrict u2_p,
  float * restrict u_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_float u2 = { u2_p + n_x*1 + n_y * xdim0_poisson_kernel_update*1 + n_z * xdim0_poisson_kernel_update * ydim0_poisson_kernel_update*1, xdim0_poisson_kernel_update, ydim0_poisson_kernel_update};
        ptr_float u = { u_p + n_x*1 + n_y * xdim1_poisson_kernel_update*1 + n_z * xdim1_poisson_kernel_update * ydim1_poisson_kernel_update*1, xdim1_poisson_kernel_update, ydim1_poisson_kernel_update};
        
  OPS_ACC(u, 0,0,0) = OPS_ACC(u2, 0,0,0);

      }
    }
  }
}
