//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim1_poisson_kernel_populate;
int xdim2_poisson_kernel_populate;
int xdim3_poisson_kernel_populate;

//user function
#pragma acc routine
inline 
void poisson_kernel_populate(const int *idx,
  ptr_float u,
  ptr_float f,
  ptr_float ref) {
  float x = dx * (float)(idx[0]);
  float y = dy * (float)(idx[1]);

  OPS_ACC(u, 0,0) = myfun(sin(M_PI*x),cos(2.0f*M_PI*y))-1.0f;
  OPS_ACC(f, 0,0) = -5.0f*M_PI*M_PI*sin(M_PI*x)*cos(2.0f*M_PI*y);
  OPS_ACC(ref, 0,0) = sin(M_PI*x)*cos(2.0f*M_PI*y);
}


void poisson_kernel_populate_c_wrapper(
  int *p_a0,
  float *p_a1,
  float *p_a2,
  float *p_a3,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a1,p_a2,p_a3)
  #pragma acc loop
  #endif
  for ( int n_y=0; n_y<y_size; n_y++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      ptr_float ptr1 = {  p_a1 + n_x*1*1 + n_y*xdim1_poisson_kernel_populate*1*1, xdim1_poisson_kernel_populate};
      ptr_float ptr2 = {  p_a2 + n_x*1*1 + n_y*xdim2_poisson_kernel_populate*1*1, xdim2_poisson_kernel_populate};
      ptr_float ptr3 = {  p_a3 + n_x*1*1 + n_y*xdim3_poisson_kernel_populate*1*1, xdim3_poisson_kernel_populate};
      poisson_kernel_populate( arg_idx,
          ptr1,ptr2,
          ptr3 );

    }
  }
}
