//
// auto-generated by ops.py
//

int xdim5_calc_ytemp_kernel;
int ydim5_calc_ytemp_kernel;
int xdim6_calc_ytemp_kernel;
int ydim6_calc_ytemp_kernel;
int xdim7_calc_ytemp_kernel;
int ydim7_calc_ytemp_kernel;


//user function



void calc_ytemp_kernel_c_wrapper(
  const int * restrict dispx,
  const int * restrict dispy,
  const int * restrict dispz,
  int * restrict idx,
  const float * restrict dt,
  float * restrict yy_p,
  float * restrict k_p,
  float * restrict ytemp_p,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        #ifdef OPS_SOA
        const ptrm_float yy = { yy_p + n_x*1 + n_y * xdim5_calc_ytemp_kernel*1 + n_z * xdim5_calc_ytemp_kernel * ydim5_calc_ytemp_kernel*1, xdim5_calc_ytemp_kernel, ydim5_calc_ytemp_kernel, zdim5_calc_ytemp_kernel};
        #else
        const ptrm_float yy = { yy_p + n_x*1 + n_y * xdim5_calc_ytemp_kernel*1 + n_z * xdim5_calc_ytemp_kernel * ydim5_calc_ytemp_kernel*1, xdim5_calc_ytemp_kernel, ydim5_calc_ytemp_kernel, 6};
        #endif
        #ifdef OPS_SOA
        ptrm_float k = { k_p + n_x*1 + n_y * xdim6_calc_ytemp_kernel*1 + n_z * xdim6_calc_ytemp_kernel * ydim6_calc_ytemp_kernel*1, xdim6_calc_ytemp_kernel, ydim6_calc_ytemp_kernel, zdim6_calc_ytemp_kernel};
        #else
        ptrm_float k = { k_p + n_x*1 + n_y * xdim6_calc_ytemp_kernel*1 + n_z * xdim6_calc_ytemp_kernel * ydim6_calc_ytemp_kernel*1, xdim6_calc_ytemp_kernel, ydim6_calc_ytemp_kernel, 6};
        #endif
        #ifdef OPS_SOA
        ptrm_float ytemp = { ytemp_p + n_x*1 + n_y * xdim7_calc_ytemp_kernel*1 + n_z * xdim7_calc_ytemp_kernel * ydim7_calc_ytemp_kernel*1, xdim7_calc_ytemp_kernel, ydim7_calc_ytemp_kernel, zdim7_calc_ytemp_kernel};
        #else
        ptrm_float ytemp = { ytemp_p + n_x*1 + n_y * xdim7_calc_ytemp_kernel*1 + n_z * xdim7_calc_ytemp_kernel * ydim7_calc_ytemp_kernel*1, xdim7_calc_ytemp_kernel, ydim7_calc_ytemp_kernel, 6};
        #endif
        

  for (int i=0;i<6;i++) {
    OPS_ACC(k, i,0,0,0) = OPS_ACC(k, i,0,0,0)* *dt;
    OPS_ACC(ytemp, i,0,0,0) = OPS_ACC(yy, i,0,0,0) + OPS_ACC(k, i,0,0,0)*0.5f;
  }


      }
    }
  }
}
