//
// auto-generated by ops.py
//

int xdim4_rtm_kernel_populate;
int ydim4_rtm_kernel_populate;
int xdim5_rtm_kernel_populate;
int ydim5_rtm_kernel_populate;
int xdim6_rtm_kernel_populate;
int ydim6_rtm_kernel_populate;


//user function



void rtm_kernel_populate_c_wrapper(
  const int * restrict dispx,
  const int * restrict dispy,
  const int * restrict dispz,
  int * restrict idx,
  float * restrict rho_p,
  float * restrict mu_p,
  float * restrict yy_p,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        ptr_float rho = { rho_p + n_x*1 + n_y * xdim4_rtm_kernel_populate*1 + n_z * xdim4_rtm_kernel_populate * ydim4_rtm_kernel_populate*1, xdim4_rtm_kernel_populate, ydim4_rtm_kernel_populate};
        ptr_float mu = { mu_p + n_x*1 + n_y * xdim5_rtm_kernel_populate*1 + n_z * xdim5_rtm_kernel_populate * ydim5_rtm_kernel_populate*1, xdim5_rtm_kernel_populate, ydim5_rtm_kernel_populate};
        #ifdef OPS_SOA
        ptrm_float yy = { yy_p + n_x*1 + n_y * xdim6_rtm_kernel_populate*1 + n_z * xdim6_rtm_kernel_populate * ydim6_rtm_kernel_populate*1, xdim6_rtm_kernel_populate, ydim6_rtm_kernel_populate, zdim6_rtm_kernel_populate};
        #else
        ptrm_float yy = { yy_p + n_x*1 + n_y * xdim6_rtm_kernel_populate*1 + n_z * xdim6_rtm_kernel_populate * ydim6_rtm_kernel_populate*1, xdim6_rtm_kernel_populate, ydim6_rtm_kernel_populate, 6};
        #endif
        




  float x = 1.0*((float)(idx[0]-nx/2)/nx);
  float y = 1.0*((float)(idx[1]-ny/2)/ny);
  float z = 1.0*((float)(idx[2]-nz/2)/nz);

  const float C = 1.0f;
  const float r0 = 0.001f;
  OPS_ACC(rho, 0,0,0) = 1000.0f;
  OPS_ACC(mu, 0,0,0) = 0.001f;






  OPS_ACC(yy, 0,0,0,0) = (1./3.)*C*exp(-(x*x+y*y+z*z)/r0);




      }
    }
  }
}
