//
// auto-generated by ops.py
//

int xdim1_poisson_kernel_populate;
int xdim2_poisson_kernel_populate;
int xdim3_poisson_kernel_populate;


//user function



void poisson_kernel_populate_c_wrapper(
  int * restrict idx,
  float * restrict u_p,
  float * restrict f_p,
  float * restrict ref_p,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      ptr_float u = { u_p + n_x*1 + n_y * xdim1_poisson_kernel_populate*1, xdim1_poisson_kernel_populate};
      ptr_float f = { f_p + n_x*1 + n_y * xdim2_poisson_kernel_populate*1, xdim2_poisson_kernel_populate};
      ptr_float ref = { ref_p + n_x*1 + n_y * xdim3_poisson_kernel_populate*1, xdim3_poisson_kernel_populate};
      
  float x = dx * (float)(idx[0]);
  float y = dy * (float)(idx[1]);

  OPS_ACC(u, 0,0) = myfun(sin(M_PI*x),cos(2.0f*M_PI*y))-1.0f;
  OPS_ACC(f, 0,0) = -5.0f*M_PI*M_PI*sin(M_PI*x)*cos(2.0f*M_PI*y);
  OPS_ACC(ref, 0,0) = sin(M_PI*x)*cos(2.0f*M_PI*y);

    }
  }
}
