//
// auto-generated by ops.py
//
__constant__ int dims_poisson_kernel_populate [4][3];
static int dims_poisson_kernel_populate_h [4][3] = {0};

//user function


__global__ void ops_poisson_kernel_populate(
float* __restrict u_p,
float* __restrict f_p,
float* __restrict ref_p,
int blockidx_start,
#ifdef OPS_MPI
int arg_idx0, int arg_idx1,
#endif
int bounds_0_l, int bounds_0_u, int bounds_1_l, int bounds_1_u,
int bounds_2_l, int bounds_2_u) {



  int n_2 = bounds_2_l + blockDim.z * blockIdx.z + threadIdx.z;
  int n_1 = bounds_1_l + blockDim.y * blockIdx.y + threadIdx.y;
  int n_0 = bounds_0_l + blockDim.x * blockIdx.x + threadIdx.x;

  int arg_idx[3]={0};
  #ifdef OPS_MPI
  arg_idx[0] = arg_idx0;
  arg_idx[1] = arg_idx1;
  #endif
  #if defined(OPS_BATCHED) && OPS_BATCHED==0
  int idx[] = {arg_idx[0]+n_1, arg_idx[1]+n_2, blockidx_start + n_0};
  #elif OPS_BATCHED==1
  int idx[] = {arg_idx[0]+n_0, arg_idx[1]+n_2, blockidx_start + n_1};
  #else
  int idx[] = {arg_idx[0]+n_0, arg_idx[1]+n_1, blockidx_start + n_2};
  #endif
  if (n_0 < bounds_0_u && n_1 < bounds_1_u && n_2 < bounds_2_u) {
    ACC<float> u(dims_poisson_kernel_populate[1][0], dims_poisson_kernel_populate[1][1], u_p + n_0 + n_1 * dims_poisson_kernel_populate[1][0] + n_2 * dims_poisson_kernel_populate[1][0] * dims_poisson_kernel_populate[1][1]);
    ACC<float> f(dims_poisson_kernel_populate[2][0], dims_poisson_kernel_populate[2][1], f_p + n_0 + n_1 * dims_poisson_kernel_populate[2][0] + n_2 * dims_poisson_kernel_populate[2][0] * dims_poisson_kernel_populate[2][1]);
    ACC<float> ref(dims_poisson_kernel_populate[3][0], dims_poisson_kernel_populate[3][1], ref_p + n_0 + n_1 * dims_poisson_kernel_populate[3][0] + n_2 * dims_poisson_kernel_populate[3][0] * dims_poisson_kernel_populate[3][1]);
    
  float x = dx * (float)(idx[0]);
  float y = dy * (float)(idx[1]);

  u(0,0) = myfun(sin(M_PI*x),cos(2.0f*M_PI*y))-1.0f;
  f(0,0) = -5.0f*M_PI*M_PI*sin(M_PI*x)*cos(2.0f*M_PI*y);
  ref(0,0) = sin(M_PI*x)*cos(2.0f*M_PI*y);

  }

}

// host stub function
#ifndef OPS_LAZY
void ops_par_loop_poisson_kernel_populate(char const *name, ops_block block, int dim, int* range,
 ops_arg arg0, ops_arg arg1, ops_arg arg2, ops_arg arg3) {
const int blockidx_start = 0; const int blockidx_end = block->count;
#ifdef OPS_BATCHED
const int batch_size = block->count;
#endif
#else
void ops_par_loop_poisson_kernel_populate_execute(const char *name, ops_block block, int blockidx_start, int blockidx_end, int dim, int *range, int nargs, ops_arg* args) {
  #ifdef OPS_BATCHED
  const int batch_size = OPS_BATCH_SIZE;
  #endif
  ops_arg arg0 = args[0];
  ops_arg arg1 = args[1];
  ops_arg arg2 = args[2];
  ops_arg arg3 = args[3];
  #endif

  //Timing
  double __t1,__t2,__c1,__c2;

  #ifndef OPS_LAZY
  ops_arg args[4] = { arg0, arg1, arg2, arg3};


  #endif

  #if defined(CHECKPOINTING) && !defined(OPS_LAZY)
  if (!ops_checkpointing_before(args,4,range,0)) return;
  #endif

  if (OPS_instance::getOPSInstance()->OPS_diags > 1) {
    ops_timing_realloc(0,"poisson_kernel_populate");
    OPS_instance::getOPSInstance()->OPS_kernels[0].count++;
    ops_timers_core(&__c2,&__t2);
  }

  #ifdef OPS_DEBUG
  ops_register_args(args, "poisson_kernel_populate");
  #endif


  //compute locally allocated range for the sub-block
  int start[2];
  int end[2];
  int arg_idx[2];
  #if defined(OPS_LAZY) || !defined(OPS_MPI)
  for ( int n=0; n<2; n++ ){
    start[n] = range[2*n];end[n] = range[2*n+1];
  }
  #else
  if (compute_ranges(args, 4,block, range, start, end, arg_idx) < 0) return;
  #endif

  #ifdef OPS_MPI
  sub_dat_list sd = OPS_sub_dat_list[args[3].dat->index];
  arg_idx[0] = MAX(0,sd->decomp_disp[0]);
  arg_idx[1] = MAX(0,sd->decomp_disp[1]);
  #else //OPS_MPI
  arg_idx[0] = 0;
  arg_idx[1] = 0;
  #endif //OPS_MPI

  #ifdef OPS_BATCHED
  const int bounds_0_l = OPS_BATCHED == 0 ? 0 : start[(OPS_BATCHED>0)+-1];
  const int bounds_0_u = OPS_BATCHED == 0 ? MIN(batch_size,block->count-blockidx_start) : end[(OPS_BATCHED>0)+-1];
  const int bounds_1_l = OPS_BATCHED == 1 ? 0 : start[(OPS_BATCHED>1)+0];
  const int bounds_1_u = OPS_BATCHED == 1 ? MIN(batch_size,block->count-blockidx_start) : end[(OPS_BATCHED>1)+0];
  const int bounds_2_l = OPS_BATCHED == 2 ? 0 : start[(OPS_BATCHED>2)+1];
  const int bounds_2_u = OPS_BATCHED == 2 ? MIN(batch_size,block->count-blockidx_start) : end[(OPS_BATCHED>2)+1];
  #else
  const int bounds_0_l = start[0];
  const int bounds_0_u = end[0];
  const int bounds_1_l = start[1];
  const int bounds_1_u = end[1];
  const int bounds_2_l = 0;
  const int bounds_2_u = blockidx_end-blockidx_start;
  #endif
  if (args[1].dat->size[0] != dims_poisson_kernel_populate_h[1][0] || args[1].dat->size[1] != dims_poisson_kernel_populate_h[1][1] || args[1].dat->size[2] != dims_poisson_kernel_populate_h[1][2] || args[2].dat->size[0] != dims_poisson_kernel_populate_h[2][0] || args[2].dat->size[1] != dims_poisson_kernel_populate_h[2][1] || args[2].dat->size[2] != dims_poisson_kernel_populate_h[2][2] || args[3].dat->size[0] != dims_poisson_kernel_populate_h[3][0] || args[3].dat->size[1] != dims_poisson_kernel_populate_h[3][1] || args[3].dat->size[2] != dims_poisson_kernel_populate_h[3][2]) {
    dims_poisson_kernel_populate_h[1][0] = args[1].dat->size[0];
    dims_poisson_kernel_populate_h[1][1] = args[1].dat->size[1];
    dims_poisson_kernel_populate_h[1][2] = args[1].dat->size[2];
    dims_poisson_kernel_populate_h[2][0] = args[2].dat->size[0];
    dims_poisson_kernel_populate_h[2][1] = args[2].dat->size[1];
    dims_poisson_kernel_populate_h[2][2] = args[2].dat->size[2];
    dims_poisson_kernel_populate_h[3][0] = args[3].dat->size[0];
    dims_poisson_kernel_populate_h[3][1] = args[3].dat->size[1];
    dims_poisson_kernel_populate_h[3][2] = args[3].dat->size[2];
    cutilSafeCall(cudaMemcpyToSymbol( dims_poisson_kernel_populate, dims_poisson_kernel_populate_h, sizeof(dims_poisson_kernel_populate)));
  }

  //set up initial pointers

  float * __restrict__ u_p = (float *)(args[1].data_d + args[1].dat->base_offset + blockidx_start * args[1].dat->batch_offset);

  float * __restrict__ f_p = (float *)(args[2].data_d + args[2].dat->base_offset + blockidx_start * args[2].dat->batch_offset);

  float * __restrict__ ref_p = (float *)(args[3].data_d + args[3].dat->base_offset + blockidx_start * args[3].dat->batch_offset);



  int x_size = MAX(0,bounds_0_u-bounds_0_l);
  int y_size = MAX(0,bounds_1_u-bounds_1_l);
  int z_size = MAX(0,bounds_2_u-bounds_2_l);

  dim3 grid( (x_size-1)/OPS_instance::getOPSInstance()->OPS_block_size_x+ 1, (y_size-1)/OPS_instance::getOPSInstance()->OPS_block_size_y + 1, (z_size-1)/OPS_instance::getOPSInstance()->OPS_block_size_z+1);
  dim3 tblock(MIN(OPS_instance::getOPSInstance()->OPS_block_size_x, x_size), MIN(OPS_instance::getOPSInstance()->OPS_block_size_y, y_size),MIN(OPS_instance::getOPSInstance()->OPS_block_size_z, z_size));



  #ifndef OPS_LAZY
  //Halo Exchanges
  ops_H_D_exchanges_device(args, 4);
  ops_halo_exchanges(args,4,range);
  ops_H_D_exchanges_device(args, 4);
  #endif

  if (OPS_instance::getOPSInstance()->OPS_diags > 1) {
    ops_timers_core(&__c1,&__t1);
    OPS_instance::getOPSInstance()->OPS_kernels[0].mpi_time += __t1-__t2;
  }


  //call kernel wrapper function, passing in pointers to data
  if (x_size > 0 && y_size > 0)
    ops_poisson_kernel_populate<<<grid, tblock >>> (  u_p,
         f_p, ref_p,         blockidx_start,
#ifdef OPS_MPI
         arg_idx[0], arg_idx[1], blockidx_start,
#endif
         bounds_0_l, bounds_0_u, bounds_1_l, bounds_1_u,
         bounds_2_l, bounds_2_u);

  cutilSafeCall(cudaGetLastError());

  if (OPS_instance::getOPSInstance()->OPS_diags>1) {
    cutilSafeCall(cudaDeviceSynchronize());
  }

  if (OPS_instance::getOPSInstance()->OPS_diags > 1) {
    ops_timers_core(&__c2,&__t2);
    OPS_instance::getOPSInstance()->OPS_kernels[0].time += __t2-__t1;
  }
  #ifndef OPS_LAZY
  ops_set_dirtybit_device(args, 4);
  ops_set_halo_dirtybit3(&args[1],range);
  ops_set_halo_dirtybit3(&args[2],range);
  ops_set_halo_dirtybit3(&args[3],range);
  #endif

  if (OPS_instance::getOPSInstance()->OPS_diags > 1) {
    //Update kernel record
    ops_timers_core(&__c1,&__t1);
    OPS_instance::getOPSInstance()->OPS_kernels[0].mpi_time += __t1-__t2;
    OPS_instance::getOPSInstance()->OPS_kernels[0].transfer += ops_compute_transfer(dim, start, end, &arg1);
    OPS_instance::getOPSInstance()->OPS_kernels[0].transfer += ops_compute_transfer(dim, start, end, &arg2);
    OPS_instance::getOPSInstance()->OPS_kernels[0].transfer += ops_compute_transfer(dim, start, end, &arg3);
  }
}

#ifdef OPS_LAZY
void ops_par_loop_poisson_kernel_populate(char const *name, ops_block block, int dim, int* range,
 ops_arg arg0, ops_arg arg1, ops_arg arg2, ops_arg arg3) {
  ops_kernel_descriptor *desc = (ops_kernel_descriptor *)malloc(sizeof(ops_kernel_descriptor));
  desc->name = name;
  desc->block = block;
  desc->dim = dim;
  desc->device = 1;
  desc->index = 0;
  desc->hash = 5381;
  desc->hash = ((desc->hash << 5) + desc->hash) + 0;
  for ( int i=0; i<4; i++ ){
    desc->range[i] = range[i];
    desc->orig_range[i] = range[i];
    desc->hash = ((desc->hash << 5) + desc->hash) + range[i];
  }
  desc->nargs = 4;
  desc->args = (ops_arg*)malloc(4*sizeof(ops_arg));
  desc->args[0] = arg0;
  desc->args[1] = arg1;
  desc->hash = ((desc->hash << 5) + desc->hash) + arg1.dat->index;
  desc->args[2] = arg2;
  desc->hash = ((desc->hash << 5) + desc->hash) + arg2.dat->index;
  desc->args[3] = arg3;
  desc->hash = ((desc->hash << 5) + desc->hash) + arg3.dat->index;
  desc->function = ops_par_loop_poisson_kernel_populate_execute;
  if (OPS_instance::getOPSInstance()->OPS_diags > 1) {
    ops_timing_realloc(0,"poisson_kernel_populate");
  }
  ops_enqueue_kernel(desc);
}
#endif
